# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        mainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menuDane = QtWidgets.QMenu(self.menubar)
        self.menuDane.setObjectName("menuDane")
        self.menuWykres = QtWidgets.QMenu(self.menubar)
        self.menuWykres.setObjectName("menuWykres")
        mainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWindow)
        self.statusbar.setObjectName("statusbar")
        mainWindow.setStatusBar(self.statusbar)
        self.actionPobierz_dane = QtWidgets.QAction(mainWindow)
        self.actionPobierz_dane.setObjectName("actionPobierz_dane")
        self.actionWyswietl_dane = QtWidgets.QAction(mainWindow)
        self.actionWyswietl_dane.setObjectName("actionWyswietl_dane")
        self.actionUstaw_zakres_dat = QtWidgets.QAction(mainWindow)
        self.actionUstaw_zakres_dat.setObjectName("actionUstaw_zakres_dat")
        self.actionWy_wietl_wykres_dla_powiatu = QtWidgets.QAction(mainWindow)
        self.actionWy_wietl_wykres_dla_powiatu.setObjectName("actionWy_wietl_wykres_dla_powiatu")
        self.actionZamknij = QtWidgets.QAction(mainWindow)
        self.actionZamknij.setObjectName("actionZamknij")
        self.menuDane.addAction(self.actionPobierz_dane)
        self.menuDane.addAction(self.actionUstaw_zakres_dat)
        self.menuDane.addAction(self.actionWyswietl_dane)
        self.menuDane.addSeparator()
        self.menuDane.addAction(self.actionZamknij)
        self.menuWykres.addAction(self.actionWy_wietl_wykres_dla_powiatu)
        self.menubar.addAction(self.menuDane.menuAction())
        self.menubar.addAction(self.menuWykres.menuAction())

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "COVID APP"))
        self.menuDane.setTitle(_translate("mainWindow", "Dane"))
        self.menuWykres.setTitle(_translate("mainWindow", "Wykres"))
        self.actionPobierz_dane.setText(_translate("mainWindow", "Pobierz dane"))
        self.actionWyswietl_dane.setText(_translate("mainWindow", "Wyświetl dane w tabeli"))
        self.actionUstaw_zakres_dat.setText(_translate("mainWindow", "Ustaw zakres dat"))
        self.actionWy_wietl_wykres_dla_powiatu.setText(_translate("mainWindow", "Wyświetl wykres dla powiatu"))
        self.actionZamknij.setText(_translate("mainWindow", "Zamknij"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())
